export const redirects = JSON.parse("{}")

export const routes = Object.fromEntries([
  ["/", { loader: () => import(/* webpackChunkName: "index.html" */"/Users/jenkin/Desktop/adminfyy.github.io/vdocs/README.md"), meta: {"title":""} }],
  ["/blog/", { loader: () => import(/* webpackChunkName: "blog_index.html" */"/Users/jenkin/Desktop/adminfyy.github.io/vdocs/blog/README.md"), meta: {"title":"博客目录"} }],
  ["/blog/ai-native-frontend-workflow.html", { loader: () => import(/* webpackChunkName: "blog_ai-native-frontend-workflow.html" */"/Users/jenkin/Desktop/adminfyy.github.io/vdocs/blog/ai-native-frontend-workflow.md"), meta: {"title":"AI Native 前端工作流：把 Codex/Agent 变成稳定产能"} }],
  ["/blog/claude-code-engineering-workflow.html", { loader: () => import(/* webpackChunkName: "blog_claude-code-engineering-workflow.html" */"/Users/jenkin/Desktop/adminfyy.github.io/vdocs/blog/claude-code-engineering-workflow.md"), meta: {"title":"Claude Code 工程化工作流：从需求到 PR 的可复制路径"} }],
  ["/blog/claude-code-large-repo-debug-refactor.html", { loader: () => import(/* webpackChunkName: "blog_claude-code-large-repo-debug-refactor.html" */"/Users/jenkin/Desktop/adminfyy.github.io/vdocs/blog/claude-code-large-repo-debug-refactor.md"), meta: {"title":"Claude Code 在大型前端仓库的调试与重构方法"} }],
  ["/blog/claude-code-multi-agent-strategy.html", { loader: () => import(/* webpackChunkName: "blog_claude-code-multi-agent-strategy.html" */"/Users/jenkin/Desktop/adminfyy.github.io/vdocs/blog/claude-code-multi-agent-strategy.md"), meta: {"title":"Claude Code 多代理协作：任务切片、并行执行与结果合并"} }],
  ["/blog/claude-code-security-governance.html", { loader: () => import(/* webpackChunkName: "blog_claude-code-security-governance.html" */"/Users/jenkin/Desktop/adminfyy.github.io/vdocs/blog/claude-code-security-governance.md"), meta: {"title":"Claude Code 安全边界与风险治理：团队落地必读"} }],
  ["/blog/code-lab.html", { loader: () => import(/* webpackChunkName: "blog_code-lab.html" */"/Users/jenkin/Desktop/adminfyy.github.io/vdocs/blog/code-lab.md"), meta: {"title":"Pattern 代码示例集"} }],
  ["/blog/codex-agent-workflow.html", { loader: () => import(/* webpackChunkName: "blog_codex-agent-workflow.html" */"/Users/jenkin/Desktop/adminfyy.github.io/vdocs/blog/codex-agent-workflow.md"), meta: {"title":"Codex Agent 工作流：需求到交付的最短路径"} }],
  ["/blog/codex-cli-to-pr.html", { loader: () => import(/* webpackChunkName: "blog_codex-cli-to-pr.html" */"/Users/jenkin/Desktop/adminfyy.github.io/vdocs/blog/codex-cli-to-pr.md"), meta: {"title":"从 Codex CLI 到 PR：一套可复用交付清单"} }],
  ["/blog/codex-prompt-debugging.html", { loader: () => import(/* webpackChunkName: "blog_codex-prompt-debugging.html" */"/Users/jenkin/Desktop/adminfyy.github.io/vdocs/blog/codex-prompt-debugging.md"), meta: {"title":"Codex Prompt 调试手册：从“说不清”到“可执行”"} }],
  ["/blog/frontend-architecture-decision-playbook.html", { loader: () => import(/* webpackChunkName: "blog_frontend-architecture-decision-playbook.html" */"/Users/jenkin/Desktop/adminfyy.github.io/vdocs/blog/frontend-architecture-decision-playbook.md"), meta: {"title":"前端架构决策手册：不是“最先进”，而是“最匹配”"} }],
  ["/blog/frontend-engineering-philosophy.html", { loader: () => import(/* webpackChunkName: "blog_frontend-engineering-philosophy.html" */"/Users/jenkin/Desktop/adminfyy.github.io/vdocs/blog/frontend-engineering-philosophy.md"), meta: {"title":"前端工程理念：快、稳、简，不做无效复杂化"} }],
  ["/blog/frontend-trends-2026-practice-map.html", { loader: () => import(/* webpackChunkName: "blog_frontend-trends-2026-practice-map.html" */"/Users/jenkin/Desktop/adminfyy.github.io/vdocs/blog/frontend-trends-2026-practice-map.md"), meta: {"title":"2026 前端热点实战图：怎么用、何时用、为什么用"} }],
  ["/blog/legacy-notes.html", { loader: () => import(/* webpackChunkName: "blog_legacy-notes.html" */"/Users/jenkin/Desktop/adminfyy.github.io/vdocs/blog/legacy-notes.md"), meta: {"title":"旧站内容归档"} }],
  ["/blog/mediator-pattern.html", { loader: () => import(/* webpackChunkName: "blog_mediator-pattern.html" */"/Users/jenkin/Desktop/adminfyy.github.io/vdocs/blog/mediator-pattern.md"), meta: {"title":"中介者模式（Mediator）"} }],
  ["/blog/publish-subscribe.html", { loader: () => import(/* webpackChunkName: "blog_publish-subscribe.html" */"/Users/jenkin/Desktop/adminfyy.github.io/vdocs/blog/publish-subscribe.md"), meta: {"title":"Observer 与 Publish/Subscribe"} }],
  ["/blog/wechat-open-tag-launch-app.html", { loader: () => import(/* webpackChunkName: "blog_wechat-open-tag-launch-app.html" */"/Users/jenkin/Desktop/adminfyy.github.io/vdocs/blog/wechat-open-tag-launch-app.md"), meta: {"title":"H5 launch-app：微信开放标签 wx-open-launch-app 原理与实战"} }],
  ["/404.html", { loader: () => import(/* webpackChunkName: "404.html" */"/Users/jenkin/Desktop/adminfyy.github.io/vdocs/.vuepress/.temp/pages/404.html.vue"), meta: {"title":""} }],
]);
